# Generated by Django 4.0.6 on 2022-07-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Honda', 'Honda'), ('Haval', 'Haval'), ('Gelly', 'Gelly'), ('Cherry', 'Cherry'), ('Volkswagen', 'Volkswagen'), ('Audi', 'Audi'), ('Skoda', 'Skoda')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_drive', models.CharField(choices=[('2wd', '4wd'), ('2wd', '4wd')], max_length=5)),
                ('transmission', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Robotic', 'Robotic'), ('Auto', 'Auto')], max_length=10)),
                ('type', models.CharField(choices=[('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Crossover', 'Crossover'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Sports Car', 'Sports Car'), ('Coupe', 'Coupe')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Atmospheric', 'Atmospheric'), ('Turbo', 'Turbo')], max_length=11)),
                ('volume', models.CharField(choices=[('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5')], max_length=3)),
                ('horsepower', models.CharField(choices=[('126', '126'), ('150', '150'), ('220', '220'), ('250', '250'), ('350', '350')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carbrand')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.engine')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cartype')),
            ],
        ),
    ]
