# Generated by Django 4.0.6 on 2022-08-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Gass', 'Gass'), ('Diesel', 'Diesel')], default='Petrol', max_length=6),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carbrand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='wheel_drive',
            field=models.CharField(choices=[('4wd', '4wd'), ('2wd', '2wd')], max_length=5),
        ),
    ]
