# Generated by Django 4.0.6 on 2022-08-08 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_engine_fuel_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
