# Generated by Django 4.0.5 on 2022-06-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Text')),
                ('publication_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
